mysite/mysite/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path, re_path, include, reverse
from .views import HomePage

urlpatterns = [
    re_path(r'^$', HomePage.as_view(), name='home'),
    re_path(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('registry.urls', namespace='registry')),
    path('teams/', include('team.urls', namespace='team')),
]

mysite/registry/urls.py
from django.urls import path, re_path
from . import views

app_name = 'registery'

urlpatterns = [
    path('companies/',views.CompanyListView.as_view(), name='company_list'),
    re_path(r'^company/(?P<pk>\d+)$', views.CompanyDetailView.as_view(), name='company_detail'),
    re_path(r'^company/add$', views.CompanyCreateView.as_view(), name='company_add'),
    re_path(r'^company/update/(?P<pk>\d+)$', views.CompanyUpdateView.as_view(), name='company_update'),
    re_path(r'^company/delete/(?P<pk>\d+)$', views.CompanyDeleteView.as_view(), name='company_delete'),
    re_path(r'^employee/add$', views.EmployeeUserCreateView.as_view(), name='employee_add'),
    re_path(r'^profile/edit/(?P<pk>\d+)$', views.EmployeeUserUpdateView.as_view(), name='employee_edit'),
    re_path(r'^employees/$', views.EmployeeUserListView.as_view(), name='employee_list'),
    re_path(r'^employee/delete/(?P<pk>\d+)$', views.EmployeeUserDeleteView.as_view(), name='employee_delete'),
]

mysite/team/urls.py
from django.urls import path, re_path
from . import views

app_name = 'team'

urlpatterns = [
    re_path(r'^all$', views.TeamListView.as_view(), name='team_list'),
    re_path(r'^add$', views.TeamCreateView.as_view(), name='team_add'),
    re_path(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    re_path(r'^edit/(?P<pk>\d+)', views.TeamUpdateView.as_view(), name='team_edit'),
    re_path(r'^delete/(?P<pk>\d+)', views.TeamDeleteView.as_view(), name='team_delete'),
]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <meta charset="utf-8">
  <title>
    MySite |
    {% block title_block %}

    {% endblock %}

  </title>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mynav">
      <a class="navbar-brand mynav" href="{% url 'home' %}">MySite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registry:company_list' %}" class='btn btn-simple'>Companies List</a>
          </li>
          {% if user.is_authenticated %}

          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registry:company_add' %}" class='btn btn-simple'>Add Company</a>
          </li>
          {% endif %}

          {% if user.is_admin %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Manage
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'registry:employee_list' %}">Employee List</a>
              <a class="dropdown-item" href="{% url 'registry:employee_add' %}">Add Employee</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'team:team_list' %}">Team List</a>
              <a class="dropdown-item" href="{% url 'team:team_add' %}">Add Team</a>
            </div>
          </li>
          {% endif %}
          {% if user.team or user.team_member.all %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Team Details
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for team in user.team_member.all %}
              <a class="dropdown-item" href="{% url 'team:team_detail' team.id %}">{{team}}</a>
              {% endfor %}
              {% if not user.team in user.team_member %}
              <a class="dropdown-item" href="{% url 'team:team_detail' user.team.id %}">{{user.team}}</a>
              {% endif %}
            </div>
          </li>
          {% endif %}

          {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account Details
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <span class="dropdown-item-text">{{ user.email }}</span>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'registry:employee_edit' user.id %}">Update Profile</a>
              <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </div>

    </nav>
  </div>

  <div class="container">
    {% block body %}

    {% endblock %}
  </div>
</body>

</html>

mysite/templates/index.html
{% extends "base.html" %}

{% block title_block %}
HomePage
{% endblock %}

{% block body %}
<div class="jumbotron text-center">
  <h1>Welcome to Registry!</h1>
</div>
<div class="container">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
    irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
    irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur
    adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
    voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}