mysite/mysite/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path, re_path, include, reverse
from .views import HomePage

urlpatterns = [
    re_path(r'^$', HomePage.as_view(), name='home'),
    re_path(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('registry.urls', namespace='registry')),
    path('teams/', include('team.urls', namespace='team')),
]

mysite/team/urls.py
from django.urls import path, re_path
from . import views

app_name = 'team'

urlpatterns = [
    re_path(r'^all$', views.TeamListView.as_view(), name='team_list'),
    re_path(r'^add$', views.TeamCreateView.as_view(), name='team_add'),
    re_path(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    re_path(r'^edit/(?P<pk>\d+)', views.TeamUpdateView.as_view(), name='team_edit'),
    re_path(r'^delete/(?P<pk>\d+)', views.TeamDeleteView.as_view(), name='team_delete'),
]

mysite/team/models.py
from django.db import models
from django.urls import reverse
from registry.models import Company, EmployeeUser

class Team(models.Model):
    name = models.CharField(max_length=250, blank=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='teams')
    lead = models.OneToOneField(EmployeeUser, on_delete=models.CASCADE, related_name='team')
    members = models.ManyToManyField(EmployeeUser, related_name='team_member')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team:team_list')

mysite/team/forms.py
from django import forms
from . models import Team
from django.contrib.auth import get_user_model
User = get_user_model()

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('name', 'lead', 'members')

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = 'Team Name'
        self.fields['lead'].label = 'Team Lead'
        self.fields['lead'].queryset = User.objects.filter(company=user.company)
        self.fields['members'] = forms.ModelMultipleChoiceField(
            label='Team Members:',
            widget=forms.CheckboxSelectMultiple,
            queryset=User.objects.filter(company=user.company)
        )

        if user.team and (not user.is_admin) :
            self.fields['lead'].widget.attrs['disabled'] = True

mysite/team/views.py
from django.urls import reverse_lazy
from braces import views as auth_views
from django.views import generic #TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core import exceptions
from . import models
from .forms import TeamForm
from django.contrib.auth import get_user_model
User = get_user_model()

#Team CRUD Classes
class TeamCreateView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.CreateView):
    model = models.Team
    form_class = TeamForm

    def test_func(self, user):
        if user.is_admin:
            return True
        else:
            raise exceptions.PermissionDenied

    def get_form_kwargs(self, **kwargs):
        form_kwargs = super().get_form_kwargs(**kwargs)
        form_kwargs["user"] = self.request.user
        return form_kwargs

    def form_valid(self, form):
        self.team = form.save(commit=False)
        self.team.company = self.request.user.company
        self.team.save()
        return super().form_valid(form)


class TeamListView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.ListView):
    model = models.Team
    context_object_name = 'teams'

    def get_queryset(self):
        return models.Team.objects.filter(company=self.request.user.company)

    def test_func(self, user):
        if user.is_admin:
            return True
        else:
            raise exceptions.PermissionDenied


class TeamDetailView(auth_views.LoginRequiredMixin,generic.DetailView):
    context_object_name = 'team_details'
    model = models.Team


class TeamUpdateView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.UpdateView):
    model = models.Team
    form_class = TeamForm

    def get_form_kwargs(self, **kwargs):
        form_kwargs = super().get_form_kwargs(**kwargs)
        form_kwargs["user"] = self.request.user
        return form_kwargs

    def test_func(self, user):
        if user.is_admin:
            return True
        elif self.get_object().lead == user:
            return True
        else:
            raise exceptions.PermissionDenied



class TeamDeleteView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.DeleteView):
    model = models.Team
    success_url = reverse_lazy('team:team_list')

    def test_func(self, user):
        if user.is_admin:
            return True
        else:
            raise exceptions.PermissionDenied

mysite/team/templates/team/team_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron">

  <h1>Delete Team: {{team.name }}?</h1>

</div>
<div class="container">
<p>Are you sure to delete Team?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'team:team_detail' pk=team.id %} ">Cancel</a>
  </form>
</div>
{% endblock %}

mysite/team/templates/team/team_detail.html
{% extends 'base.html' %}

{% block title_block %}
Team DetailPage
{% endblock %}

{% block body %}

<div class="jumbotron text-center">
  <h1>{{ team_details.name }}'s Details</h1>
</div>
<div class="container">
  <div class="card w-75">
    <div class="card-header">Team Name</div>
    <div class="card-body">
      <h5 class="card-title">{{ team_details.name}}</h5>
    </div>
  </div>
  <p />
  <div class="card w-75">
    <div class="card-header">Team Lead</div>
    <div class="card-body">
      <h5 class="card-title">{{ team_details.lead}}</h5>
    </div>
  </div>
  <p />
  <div class="card w-75">
    <div class="card-header">Team Members</div>
    <div class="card-body">
      <h5 class="card-title">
        {% for mem in team_details.members.all %}
        <p>{{ mem }}</p>
        {% endfor %}
      </h5>
    </div>
  </div>
</div>
{% if user.team == team_details %}
<p></p><a href="{% url 'team:team_edit' team_details.id %}" class="btn btn-warning">Update</a>
{% endif %}

{% endblock %}

mysite/team/templates/team/team_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title_block%}

{% if not form.instance.pk %}
Add Team
{% else %}
Update Team
{% endif %}
{% endblock %}


{% block body %}

<h1>
  <div class="jumbotron">
    {% if not form.instance.pk %}
    Add Team
    {% else %}
    Update Team
    {% endif %}
</h1>
</div>
<div class="container">
  <form class="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

mysite/team/templates/team/team_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title_block %}
Employees List
{% endblock %}

{% block body %}
<div class="jumbotron">
  <h1>List of Compant Employees</h1>
</div>
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>TeamName</th>
        <th>Lead</th>
        <th>Members</th>
        <th class="text-center">Edit/Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for team in teams %}
      <tr>
        <td>
          {{ team.name }}
        </td>
        <td>
          {{ team.lead }}
        </td>
        <td>
          {% for mem in team.members.all %}
          <p>{{ mem }}</p>
          {% endfor %}
        </td>
        <td class="text-center">
          <a href="{% url 'team:team_edit' pk=team.id %}"><span class="fas fa-pencil-alt" title="Edit Team"></span></a>
          /
          <a href="{% url 'team:team_delete' pk=team.id %}"><span class="fas fa-trash" title="Delete Team"></span></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
</div>
{% endblock %}