mysite/mysite/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path, re_path, include, reverse
from .views import HomePage

urlpatterns = [
    re_path(r'^$', HomePage.as_view(), name='home'),
    re_path(r'^admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('registry.urls', namespace='registry')),
    path('teams/', include('team.urls', namespace='team')),
]

mysite/registry/urls.py
from django.urls import path, re_path
from . import views

app_name = 'registery'

urlpatterns = [
    path('companies/',views.CompanyListView.as_view(), name='company_list'),
    re_path(r'^company/(?P<pk>\d+)$', views.CompanyDetailView.as_view(), name='company_detail'),
    re_path(r'^company/add$', views.CompanyCreateView.as_view(), name='company_add'),
    re_path(r'^company/update/(?P<pk>\d+)$', views.CompanyUpdateView.as_view(), name='company_update'),
    re_path(r'^company/delete/(?P<pk>\d+)$', views.CompanyDeleteView.as_view(), name='company_delete'),
    re_path(r'^employee/add$', views.EmployeeUserCreateView.as_view(), name='employee_add'),
    re_path(r'^profile/edit/(?P<pk>\d+)$', views.EmployeeUserUpdateView.as_view(), name='employee_edit'),
    re_path(r'^employees/$', views.EmployeeUserListView.as_view(), name='employee_list'),
    re_path(r'^employee/delete/(?P<pk>\d+)$', views.EmployeeUserDeleteView.as_view(), name='employee_delete'),
]

mysite/team/urls.py
from django.urls import path, re_path
from . import views

app_name = 'team'

urlpatterns = [
    re_path(r'^all$', views.TeamListView.as_view(), name='team_list'),
    re_path(r'^add$', views.TeamCreateView.as_view(), name='team_add'),
    re_path(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    re_path(r'^edit/(?P<pk>\d+)', views.TeamUpdateView.as_view(), name='team_edit'),
    re_path(r'^delete/(?P<pk>\d+)', views.TeamDeleteView.as_view(), name='team_delete'),
]

mysite/registry/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


class Company(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False, null=False)
    address = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('registry:company_detail', kwargs={'pk':self.pk})


class EmployeeUser(AbstractUser):
    is_admin = models.BooleanField('Company Admin', default=False)
    address = models.TextField(blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='employees', blank=False, null=True)

    def __init__(self, *args, **kwargs):
        self._meta.get_field('email').blank = False
        self._meta.get_field('email')._unique = True
        super().__init__(*args, **kwargs)

    def __str__(self):
        return self.email + " - " + self.get_full_name()

    def get_absolute_url(self):
        return reverse('registry:employee_list')

mysite/registry/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import EmployeeUser, Company
from django.contrib.auth import get_user_model
User = get_user_model()


class EmployeeCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = EmployeeUser
        fields = ['username', 'email']


class EmployeeChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = EmployeeUser
        fields = ['username', 'email']


class CompanyForm(forms.ModelForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = Company
        fields = ('name', 'address', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = 'Company Name'
        self.fields['address'].label = 'Company Address'
        self.fields['email'].label = "Company's Admin Email"

mysite/registry/views.py
from django.urls import reverse_lazy
from braces import views as auth_views
from django.views import generic #TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core import exceptions
from django.db import transaction
from . import models
from .forms import CompanyForm
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
User = get_user_model()


# Company CRUD Classed
class CompanyListView(generic.ListView):
    context_object_name = 'companys'
    model = models.Company


class CompanyDetailView(auth_views.SuperuserRequiredMixin, generic.DetailView):
    context_object_name = 'company_details'
    model = models.Company
    template_name = 'registry/company_detail.html'


class CompanyCreateView(auth_views.SuperuserRequiredMixin, generic.CreateView):
    model = models.Company
    form_class = CompanyForm

    def form_valid(self, form):
        self.email = form.cleaned_data['email']

        with transaction.atomic():
            self.company = form.save()

            my_password = User.objects.make_random_password(length=10)
            user = User.objects.create_user(username=self.email, email=self.email, password=my_password)
            if user:
                user.is_admin = True
                user.company = self.company
                send_mail(
                    subject="Welcome to MySite",
                    message=f"Here are the details \n Login:{user.email} \n Password: {my_password}",
                    from_email='admin@mysite.com',
                    recipient_list=[user.email,],
                    fail_silently=False
                )
                user.save()

        return super().form_valid(form)


class CompanyUpdateView(auth_views.SuperuserRequiredMixin, generic.UpdateView):
    model = models.Company
    fields = ('name', 'address')


class CompanyDeleteView(auth_views.SuperuserRequiredMixin, generic.DeleteView):
    model = models.Company
    success_url = reverse_lazy('registry:company_list')


#Employee CRUD Classes
class EmployeeUserCreateView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.CreateView):
    model = models.EmployeeUser
    fields = ('email', 'first_name', 'last_name', 'is_admin')

    def test_func(self, user):
        if user.is_admin:
            return True
        else:
            raise exceptions.PermissionDenied

    def form_valid(self, form):
        self.emp = form.save(commit=False)
        self.emp.username = self.emp.email
        self.emp.company = self.request.user.company
        my_password = User.objects.make_random_password(length=10)
        send_mail(
            subject="Welcome to MySite",
            message=f"Here are the details \n Login:{self.emp.email} \n Password: {my_password}",
            from_email='admin@mysite.com',
            recipient_list=[self.emp.email,],
            fail_silently=False
        )
        self.emp.set_password(my_password)
        self.emp.save()
        return super().form_valid(form)


class EmployeeUserUpdateView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.UpdateView):
    model = models.EmployeeUser
    fields = ('username', 'first_name', 'last_name', 'email', 'address')

    def test_func(self, user):
        if str(user.pk) == self.kwargs['pk']:
            return True
        else:
            raise exceptions.PermissionDenied


class EmployeeUserListView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.ListView):
    context_object_name = 'employeeusers'
    model = models.EmployeeUser

    def get_queryset(self):
        return User.objects.filter(company=self.request.user.company)

    def test_func(self, user):
        if user.is_admin:
            return True
        else:
            raise exceptions.PermissionDenied


class EmployeeUserDeleteView(auth_views.UserPassesTestMixin, auth_views.LoginRequiredMixin, generic.DeleteView):
    model = models.EmployeeUser
    success_url = reverse_lazy('registry:employee_list')

    def test_func(self, user):
        if user.is_admin:
            return True
        else:
            raise exceptions.PermissionDenied

mysite/registry/templates/registry/company_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron">

  <h1>Delete Company: {{company.name }}?</h1>

</div>
<div class="container">
<p>Are you sure to delete Team?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'registery:company_detail' pk=company.pk%} ">Cancel</a>
  </form>
</div>
{% endblock %}

mysite/registry/templates/registry/company_detail.html
{% extends 'base.html' %}

{% block title_block %}
Company DetailPage
{% endblock %}

{% block body %}

<div class="jumbotron">
  <h1>{{ company_details.name }}'s Details:</h1>
</div>
<div class="container">
  <p>Name: {{ company_details.name}}</p>
  <p>Address: {{ company_details.address }}</p>
</div>

<a href="{% url 'registry:company_update' company_details.id %}" class="btn btn-warning">Update</a>
<a href="{% url 'registry:company_delete' company_details.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

mysite/registry/templates/registry/company_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title_block%}

{% if not form.instance.pk %}
Create Company
{% else %}
Update Company
{% endif %}
{% endblock %}


{% block body %}
<div class="jumbotron">
  <h1>
    {% if not form.instance.pk %}
    Add Company
    {% else %}
    Company Update
    {% endif %}
  </h1>
</div>
<div class="container">
  <form class="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

mysite/registry/templates/registry/company_list.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron">
  <h1>Companies Registered</h1>
</div>
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Company Name</th>
        <th>Comapny Address</th>
      </tr>
    </thead>
    <tbody>
      {% if user.is_superuser %}
      {% for comp in companys %}
      <tr>
        <td><a href="{% url 'registry:company_detail' comp.id %}">{{ comp.name }}</a></td>
        <td>{{comp.address}}</td>
      </tr>
      {% endfor %}
      {% else %}
      {% for comp in companys %}
      <tr>
        <td>{{ comp.name }}</td>
        <td>{{comp.address}}</td>
      </tr>
      {% endfor %}
      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

mysite/registry/templates/registry/employeeuser_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron">

  <h1>Delete Employee: {{employeeuser.username }}?</h1>

</div>
<div class="container">
<p>Are you sure to delete Team?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'registery:employee_list' %} ">Cancel</a>
  </form>
</div>
{% endblock %}

mysite/registry/templates/registry/employeeuser_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title_block%}

{% if not form.instance.pk %}
Add Employee
{% else %}
Update Employee
{% endif %}
{% endblock %}


{% block body %}

<h1>
  <div class="jumbotron">
    {% if not form.instance.pk %}
    Add Employee
    {% else %}
    Company Employee
    {% endif %}
</h1>
</div>
<div class="container">
  <form class="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

mysite/registry/templates/registry/employeeuser_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title_block %}
Employees List
{% endblock %}

{% block body %}
<div class="jumbotron">
  <h1>List of Compant Employees</h1>
</div>
<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>UserName</th>
        <th>Name</th>
        <th>Email</th>
        <th class="text-center">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for emp in employeeusers %}
      <tr>
        <td>
          {{ emp.username }}
        </td>
        <td>
          {{ emp.get_full_name }}
        </td>
        <td>
          {{ emp.email }}
        </td>
        <td class="text-center">
          <a href="{% url 'registry:employee_delete' emp.id %}"><span class="fas fa-trash" title="Delete Employee"></span></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
</div>
{% endblock %}